
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `igrica`
--

-- --------------------------------------------------------

--
-- Table structure for table `phases`
--


--
-- Dumping data for table `phases`
--

INSERT INTO `phases` (`id`, `nivo_id`, `naziv`, `opis`, `blocks`, `solution`, `rules`, `hint`, `order`, `created_at`, `updated_at`) VALUES
(1, 1, 'Faza 1 – Sastavi osnovnu HTML stranicu', 'Prevuci HTML blokove na odgovarajuća mesta i napravi ispravnu osnovnu HTML stranicu.', '{\"mode\":\"dragdrop\",\"blocks\":{\"html_open\":{\"label\":\"<html>\",\"tag\":\"html\"},\"html_close\":{\"label\":\"<\\/html>\",\"tag\":\"\\/html\"},\"head_open\":{\"label\":\"<head>\",\"tag\":\"head\"},\"head_close\":{\"label\":\"<\\/head>\",\"tag\":\"\\/head\"},\"title\":{\"label\":\"<title>Moja prva stranica<\\/title>\",\"tag\":\"title\"},\"body_open\":{\"label\":\"<body>\",\"tag\":\"body\"},\"body_close\":{\"label\":\"<\\/body>\",\"tag\":\"\\/body\"},\"h1\":{\"label\":\"<h1>Zdravo svete!<\\/h1>\",\"tag\":\"h1\"},\"p\":{\"label\":\"<p>Ovo je moj prvi HTML dokument.<\\/p>\",\"tag\":\"p\"}},\"palette\":[\"html_open\",\"html_close\",\"head_open\",\"head_close\",\"title\",\"body_open\",\"body_close\",\"h1\",\"p\"],\"slots\":[\"root\",\"head\",\"body\"]}', '{\"success\":\"\\ud83c\\udf89 Ta\\u010dno! Napravio si ispravnu HTML stranicu.\"}', '[{\"type\":\"childOfTag\",\"parentTag\":\"head\",\"childTag\":\"title\"},{\"type\":\"childOfTag\",\"parentTag\":\"body\",\"childTag\":\"h1\"},{\"type\":\"childOfTag\",\"parentTag\":\"body\",\"childTag\":\"p\"},{\"type\":\"forbidChildOfTag\",\"parentTag\":\"head\",\"childTag\":\"h1\"},{\"type\":\"forbidChildOfTag\",\"parentTag\":\"head\",\"childTag\":\"p\"}]', 'Head sadrži informacije o stranici, a body sadrži ono što korisnik vidi.', 1, '2026-02-05 19:57:21', '2026-02-05 19:57:21'),
(2, 2, 'Faza 1 – Navigacioni meni', 'Napravi navigacioni meni sa tri linka koristeći listu.', '{\"mode\":\"dragdrop\",\"blocks\":{\"nav_open\":{\"label\":\"<nav>\",\"tag\":\"nav\"},\"nav_close\":{\"label\":\"<\\/nav>\",\"tag\":\"\\/nav\"},\"ul_open\":{\"label\":\"<ul>\",\"tag\":\"ul\"},\"ul_close\":{\"label\":\"<\\/ul>\",\"tag\":\"\\/ul\"},\"li_open\":{\"label\":\"<li>\",\"tag\":\"li\"},\"li_close\":{\"label\":\"<\\/li>\",\"tag\":\"\\/li\"},\"a_home\":{\"label\":\"<a href=\\\"index.html\\\">Home<\\/a>\",\"tag\":\"a\"},\"a_about\":{\"label\":\"<a href=\\\"about.html\\\">About<\\/a>\",\"tag\":\"a\"},\"a_contact\":{\"label\":\"<a href=\\\"contact.html\\\">Contact<\\/a>\",\"tag\":\"a\"},\"ol_open\":{\"label\":\"<ol>\",\"tag\":\"ol\"},\"ol_close\":{\"label\":\"<\\/ol>\",\"tag\":\"\\/ol\"},\"ul2_open\":{\"label\":\"<ul>\",\"tag\":\"ul\"},\"ul2_close\":{\"label\":\"<\\/ul>\",\"tag\":\"\\/ul\"},\"tea1\":{\"label\":\"<li>Zagrej vodu<\\/li>\",\"tag\":\"li\"},\"tea2\":{\"label\":\"<li>Ubaci \\u010daj<\\/li>\",\"tag\":\"li\"},\"tea3\":{\"label\":\"<li>Sipaj u \\u0161olju<\\/li>\",\"tag\":\"li\"},\"a_google\":{\"label\":\"<a href=\\\"https:\\/\\/google.com\\\"> Google <\\/a>\",\"tag\":\"a\"},\"target_blank\":{\"label\":\"target=\\\"_blank\\\"\",\"tag\":\"attr_target_blank\"}},\"palette\":[\"nav_open\",\"nav_close\",\"ul_open\",\"ul_close\",\"li_open\",\"li_close\",\"a_home\",\"a_about\",\"a_contact\"],\"slots\":[\"root\"]}', '{\"success\":\"\\ud83d\\ude80 Navigacija je ispravna!\"}', '[{\"type\":\"slotOrder\",\"slot\":\"root\",\"order\":[\"nav_open\",\"ul_open\",\"li_open\",\"a_home\",\"li_close\",\"li_open\",\"a_about\",\"li_close\",\"li_open\",\"a_contact\",\"li_close\",\"ul_close\",\"nav_close\"]}]', 'Link je deo stavke liste, ne obrnuto.', 1, '2026-02-05 19:57:21', '2026-02-05 19:57:21'),
(3, 2, 'Faza 2 – Izaberi pravu listu', 'Napravi listu koraka za pravljenje čaja.', '{\"mode\":\"dragdrop\",\"blocks\":{\"nav_open\":{\"label\":\"<nav>\",\"tag\":\"nav\"},\"nav_close\":{\"label\":\"<\\/nav>\",\"tag\":\"\\/nav\"},\"ul_open\":{\"label\":\"<ul>\",\"tag\":\"ul\"},\"ul_close\":{\"label\":\"<\\/ul>\",\"tag\":\"\\/ul\"},\"li_open\":{\"label\":\"<li>\",\"tag\":\"li\"},\"li_close\":{\"label\":\"<\\/li>\",\"tag\":\"\\/li\"},\"a_home\":{\"label\":\"<a href=\\\"index.html\\\">Home<\\/a>\",\"tag\":\"a\"},\"a_about\":{\"label\":\"<a href=\\\"about.html\\\">About<\\/a>\",\"tag\":\"a\"},\"a_contact\":{\"label\":\"<a href=\\\"contact.html\\\">Contact<\\/a>\",\"tag\":\"a\"},\"ol_open\":{\"label\":\"<ol>\",\"tag\":\"ol\"},\"ol_close\":{\"label\":\"<\\/ol>\",\"tag\":\"\\/ol\"},\"ul2_open\":{\"label\":\"<ul>\",\"tag\":\"ul\"},\"ul2_close\":{\"label\":\"<\\/ul>\",\"tag\":\"\\/ul\"},\"tea1\":{\"label\":\"<li>Zagrej vodu<\\/li>\",\"tag\":\"li\"},\"tea2\":{\"label\":\"<li>Ubaci \\u010daj<\\/li>\",\"tag\":\"li\"},\"tea3\":{\"label\":\"<li>Sipaj u \\u0161olju<\\/li>\",\"tag\":\"li\"},\"a_google\":{\"label\":\"<a href=\\\"https:\\/\\/google.com\\\"> Google <\\/a>\",\"tag\":\"a\"},\"target_blank\":{\"label\":\"target=\\\"_blank\\\"\",\"tag\":\"attr_target_blank\"}},\"palette\":[\"ol_open\",\"ol_close\",\"ul2_open\",\"ul2_close\",\"tea1\",\"tea2\",\"tea3\"],\"slots\":[\"root\"]}', '{\"success\":\"\\u2705 Ta\\u010dno \\u2013 za korake ide <ol>.\"}', '[{\"type\":\"slotOrder\",\"slot\":\"root\",\"order\":[\"ol_open\",\"tea1\",\"tea2\",\"tea3\",\"ol_close\"]}]', 'Pošto su u pitanju koraci, koristi se uređena lista (<ol>).', 2, '2026-02-05 19:57:21', '2026-02-05 19:57:21'),
(4, 2, 'Faza 3 – Eksterni link', 'Napravi link ka Google sajtu koji se otvara u novom tabu.', '{\"mode\":\"dragdrop\",\"blocks\":{\"nav_open\":{\"label\":\"<nav>\",\"tag\":\"nav\"},\"nav_close\":{\"label\":\"<\\/nav>\",\"tag\":\"\\/nav\"},\"ul_open\":{\"label\":\"<ul>\",\"tag\":\"ul\"},\"ul_close\":{\"label\":\"<\\/ul>\",\"tag\":\"\\/ul\"},\"li_open\":{\"label\":\"<li>\",\"tag\":\"li\"},\"li_close\":{\"label\":\"<\\/li>\",\"tag\":\"\\/li\"},\"a_home\":{\"label\":\"<a href=\\\"index.html\\\">Home<\\/a>\",\"tag\":\"a\"},\"a_about\":{\"label\":\"<a href=\\\"about.html\\\">About<\\/a>\",\"tag\":\"a\"},\"a_contact\":{\"label\":\"<a href=\\\"contact.html\\\">Contact<\\/a>\",\"tag\":\"a\"},\"ol_open\":{\"label\":\"<ol>\",\"tag\":\"ol\"},\"ol_close\":{\"label\":\"<\\/ol>\",\"tag\":\"\\/ol\"},\"ul2_open\":{\"label\":\"<ul>\",\"tag\":\"ul\"},\"ul2_close\":{\"label\":\"<\\/ul>\",\"tag\":\"\\/ul\"},\"tea1\":{\"label\":\"<li>Zagrej vodu<\\/li>\",\"tag\":\"li\"},\"tea2\":{\"label\":\"<li>Ubaci \\u010daj<\\/li>\",\"tag\":\"li\"},\"tea3\":{\"label\":\"<li>Sipaj u \\u0161olju<\\/li>\",\"tag\":\"li\"},\"a_google\":{\"label\":\"<a href=\\\"https:\\/\\/google.com\\\"> Google <\\/a>\",\"tag\":\"a\"},\"target_blank\":{\"label\":\"target=\\\"_blank\\\"\",\"tag\":\"attr_target_blank\"}},\"palette\":[\"a_google\",\"target_blank\"],\"slots\":[\"root\"]}', '{\"success\":\"\\u2705 Eksterni link se otvara u novom tabu!\"}', '[{\"type\":\"requireBlocks\",\"blocks\":[\"a_google\",\"target_blank\"]}]', NULL, 3, '2026-02-05 19:57:21', '2026-02-05 19:57:21'),
(5, 3, 'Faza 1 – Zameni divove semantičkim tagovima', 'Zameni generičke div elemente odgovarajućim semantičkim tagovima.', '{\"mode\":\"dragdrop\",\"blocks\":{\"header_open\":{\"label\":\"<header>\",\"tag\":\"header\"},\"header_close\":{\"label\":\"<\\/header>\",\"tag\":\"\\/header\"},\"nav_open\":{\"label\":\"<nav>\",\"tag\":\"nav\"},\"nav_close\":{\"label\":\"<\\/nav>\",\"tag\":\"\\/nav\"},\"main_open\":{\"label\":\"<main>\",\"tag\":\"main\"},\"main_close\":{\"label\":\"<\\/main>\",\"tag\":\"\\/main\"},\"footer_open\":{\"label\":\"<footer>\",\"tag\":\"footer\"},\"footer_close\":{\"label\":\"<\\/footer>\",\"tag\":\"\\/footer\"},\"header_blog\":{\"label\":\"<header>Blog<\\/header>\",\"tag\":\"header\"},\"article_full\":{\"label\":\"<article><h2>Prvi post<\\/h2><p>Ovo je tekst posta.<\\/p><\\/article>\",\"tag\":\"article\"},\"aside_full\":{\"label\":\"<aside><p>Reklama<\\/p><\\/aside>\",\"tag\":\"aside\"},\"footer_full\":{\"label\":\"<footer><p>\\u00a9 2026<\\/p><\\/footer>\",\"tag\":\"footer\"}},\"palette\":[\"header_open\",\"header_close\",\"nav_open\",\"nav_close\",\"main_open\",\"main_close\",\"footer_open\",\"footer_close\"],\"slots\":[\"root\"]}', '{\"success\":\"\\u2705 Semanti\\u010dki tagovi su postavljeni!\"}', '[{\"type\":\"slotOrder\",\"slot\":\"root\",\"order\":[\"header_open\",\"header_close\",\"nav_open\",\"nav_close\",\"main_open\",\"main_close\",\"footer_open\",\"footer_close\"]}]', 'Semantički tag opisuje šta sadržaj znači, ne kako izgleda.', 1, '2026-02-05 19:57:21', '2026-02-05 19:57:21'),
(6, 3, 'Faza 2 – Struktura blog stranice', 'Složi strukturu blog stranice koristeći semantičke tagove.', '{\"mode\":\"dragdrop\",\"blocks\":{\"header_open\":{\"label\":\"<header>\",\"tag\":\"header\"},\"header_close\":{\"label\":\"<\\/header>\",\"tag\":\"\\/header\"},\"nav_open\":{\"label\":\"<nav>\",\"tag\":\"nav\"},\"nav_close\":{\"label\":\"<\\/nav>\",\"tag\":\"\\/nav\"},\"main_open\":{\"label\":\"<main>\",\"tag\":\"main\"},\"main_close\":{\"label\":\"<\\/main>\",\"tag\":\"\\/main\"},\"footer_open\":{\"label\":\"<footer>\",\"tag\":\"footer\"},\"footer_close\":{\"label\":\"<\\/footer>\",\"tag\":\"\\/footer\"},\"header_blog\":{\"label\":\"<header>Blog<\\/header>\",\"tag\":\"header\"},\"article_full\":{\"label\":\"<article><h2>Prvi post<\\/h2><p>Ovo je tekst posta.<\\/p><\\/article>\",\"tag\":\"article\"},\"aside_full\":{\"label\":\"<aside><p>Reklama<\\/p><\\/aside>\",\"tag\":\"aside\"},\"footer_full\":{\"label\":\"<footer><p>\\u00a9 2026<\\/p><\\/footer>\",\"tag\":\"footer\"}},\"palette\":[\"header_blog\",\"main_open\",\"main_close\",\"article_full\",\"aside_full\",\"footer_full\"],\"slots\":[\"root\",\"main\"]}', '{\"success\":\"\\ud83c\\udf89 Sada pi\\u0161e\\u0161 HTML kao pravi web developer.\"}', '[{\"type\":\"slotOrder\",\"slot\":\"root\",\"order\":[\"header_blog\",\"main_open\",\"main_close\",\"aside_full\",\"footer_full\"]},{\"type\":\"blockInSlot\",\"slot\":\"main\",\"block\":\"article_full\"}]', '<article> ide u <main>, <aside> je pored glavnog sadržaja, <footer> je na dnu stranice.', 2, '2026-02-05 19:57:21', '2026-02-05 19:57:21');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `phases`
--

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
